version: "3.8"
services:
  database:
    restart: always
    image: "postgres:13"
    container_name: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - back


  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_back
    ports:
      - "8000:8000"
    healthcheck:
      test: curl -sS http://localhost:8000/admin/ || exit 1
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: on-failure:3
    depends_on:
      - database
    networks:
      - back
      - front

  frontend:
    restart: always
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -sS  http://localhost:3000 || exit 1
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
    depends_on:
      - backend
    networks:
      - front
      
networks:
 front:
    driver: bridge

 back:
    driver: bridge

