FROM python:3.9
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY /lib_catalog .
EXPOSE 8000
RUN RUN useradd docker  && chown -R docker /app && pip install -r requirements.txt
USER docker
ENTRYPOINT [ "/bin/sh", "-c", "./init.sh"]

   
